/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/pracsys/catkin_ws/src/baxter_common/baxter_core_msgs/msg/SEAJointState.msg
 *
 */


#ifndef BAXTER_CORE_MSGS_MESSAGE_SEAJOINTSTATE_H
#define BAXTER_CORE_MSGS_MESSAGE_SEAJOINTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace baxter_core_msgs
{
template <class ContainerAllocator>
struct SEAJointState_
{
  typedef SEAJointState_<ContainerAllocator> Type;

  SEAJointState_()
    : header()
    , name()
    , commanded_position()
    , commanded_velocity()
    , commanded_effort()
    , actual_position()
    , actual_velocity()
    , actual_effort()
    , gravity_model_effort()
    , hysteresis_model_effort()
    , crosstalk_model_effort()
    , hystState(0.0)  {
    }
  SEAJointState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , commanded_position(_alloc)
    , commanded_velocity(_alloc)
    , commanded_effort(_alloc)
    , actual_position(_alloc)
    , actual_velocity(_alloc)
    , actual_effort(_alloc)
    , gravity_model_effort(_alloc)
    , hysteresis_model_effort(_alloc)
    , crosstalk_model_effort(_alloc)
    , hystState(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_type;
  _name_type name;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _commanded_position_type;
  _commanded_position_type commanded_position;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _commanded_velocity_type;
  _commanded_velocity_type commanded_velocity;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _commanded_effort_type;
  _commanded_effort_type commanded_effort;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _actual_position_type;
  _actual_position_type actual_position;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _actual_velocity_type;
  _actual_velocity_type actual_velocity;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _actual_effort_type;
  _actual_effort_type actual_effort;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _gravity_model_effort_type;
  _gravity_model_effort_type gravity_model_effort;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _hysteresis_model_effort_type;
  _hysteresis_model_effort_type hysteresis_model_effort;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _crosstalk_model_effort_type;
  _crosstalk_model_effort_type crosstalk_model_effort;

   typedef double _hystState_type;
  _hystState_type hystState;




  typedef boost::shared_ptr< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SEAJointState_

typedef ::baxter_core_msgs::SEAJointState_<std::allocator<void> > SEAJointState;

typedef boost::shared_ptr< ::baxter_core_msgs::SEAJointState > SEAJointStatePtr;
typedef boost::shared_ptr< ::baxter_core_msgs::SEAJointState const> SEAJointStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_core_msgs::SEAJointState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_core_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'baxter_core_msgs': ['/home/pracsys/catkin_ws/src/baxter_common/baxter_core_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1bd9a7d2f17b6deeb6a528891f49eae";
  }

  static const char* value(const ::baxter_core_msgs::SEAJointState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1bd9a7d2f17b6deULL;
  static const uint64_t static_value2 = 0xeb6a528891f49eaeULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_core_msgs/SEAJointState";
  }

  static const char* value(const ::baxter_core_msgs::SEAJointState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is a message that holds data to describe the state of a set of torque controlled joints.\n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and\n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state.\n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty.\n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] commanded_position\n\
float64[] commanded_velocity\n\
float64[] commanded_effort\n\
float64[] actual_position\n\
float64[] actual_velocity\n\
float64[] actual_effort\n\
float64[] gravity_model_effort\n\
float64[] hysteresis_model_effort\n\
float64[] crosstalk_model_effort\n\
float64   hystState\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::baxter_core_msgs::SEAJointState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.commanded_position);
      stream.next(m.commanded_velocity);
      stream.next(m.commanded_effort);
      stream.next(m.actual_position);
      stream.next(m.actual_velocity);
      stream.next(m.actual_effort);
      stream.next(m.gravity_model_effort);
      stream.next(m.hysteresis_model_effort);
      stream.next(m.crosstalk_model_effort);
      stream.next(m.hystState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SEAJointState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_core_msgs::SEAJointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_core_msgs::SEAJointState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "commanded_position[]" << std::endl;
    for (size_t i = 0; i < v.commanded_position.size(); ++i)
    {
      s << indent << "  commanded_position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.commanded_position[i]);
    }
    s << indent << "commanded_velocity[]" << std::endl;
    for (size_t i = 0; i < v.commanded_velocity.size(); ++i)
    {
      s << indent << "  commanded_velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.commanded_velocity[i]);
    }
    s << indent << "commanded_effort[]" << std::endl;
    for (size_t i = 0; i < v.commanded_effort.size(); ++i)
    {
      s << indent << "  commanded_effort[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.commanded_effort[i]);
    }
    s << indent << "actual_position[]" << std::endl;
    for (size_t i = 0; i < v.actual_position.size(); ++i)
    {
      s << indent << "  actual_position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.actual_position[i]);
    }
    s << indent << "actual_velocity[]" << std::endl;
    for (size_t i = 0; i < v.actual_velocity.size(); ++i)
    {
      s << indent << "  actual_velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.actual_velocity[i]);
    }
    s << indent << "actual_effort[]" << std::endl;
    for (size_t i = 0; i < v.actual_effort.size(); ++i)
    {
      s << indent << "  actual_effort[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.actual_effort[i]);
    }
    s << indent << "gravity_model_effort[]" << std::endl;
    for (size_t i = 0; i < v.gravity_model_effort.size(); ++i)
    {
      s << indent << "  gravity_model_effort[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.gravity_model_effort[i]);
    }
    s << indent << "hysteresis_model_effort[]" << std::endl;
    for (size_t i = 0; i < v.hysteresis_model_effort.size(); ++i)
    {
      s << indent << "  hysteresis_model_effort[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.hysteresis_model_effort[i]);
    }
    s << indent << "crosstalk_model_effort[]" << std::endl;
    for (size_t i = 0; i < v.crosstalk_model_effort.size(); ++i)
    {
      s << indent << "  crosstalk_model_effort[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.crosstalk_model_effort[i]);
    }
    s << indent << "hystState: ";
    Printer<double>::stream(s, indent + "  ", v.hystState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_CORE_MSGS_MESSAGE_SEAJOINTSTATE_H
