(cl:defpackage baxter_maintenance_msgs-msg
  (:use )
  (:export
   "<UPDATESOURCES>"
   "UPDATESOURCES"
   "<UPDATESTATUS>"
   "UPDATESTATUS"
   "<UPDATESOURCE>"
   "UPDATESOURCE"
   "<TAREENABLE>"
   "TAREENABLE"
   "<TAREDATA>"
   "TAREDATA"
   "<CALIBRATEARMENABLE>"
   "CALIBRATEARMENABLE"
   "<CALIBRATEARMDATA>"
   "CALIBRATEARMDATA"
  ))

